# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cle-guen <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/11/10 12:45:15 by cle-guen          #+#    #+#              #
#    Updated: 2017/11/10 16:29:54 by cle-guen         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

FLAGS = -Wall -Wextra -Werror

SRCNAME = display_file.c

all: $(NAME)

$(NAME):
	gcc $(FLAGS) $(SRCNAME) -o ft_display_file

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all
